spring:
  jpa:
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    platform: mysql
    url: jdbc:mysql://127.0.0.1/100hashes?useUnicode=yes&characterEncoding=UTF-8&&serverTimezone=UTC
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver

